### ISSUE TITLE
freezes iTerm

### ISSUE THREAD

**Issue by bnmnetp** [isometry/alfred-tty#2]
Hi,

I'm using iTerm2 3.1.beta.9 but when I try to select a tab using the new tty workflow it just freezes up iTerm2 altogether.  I'm not able to select any tab, and I'm not able to type in the tab that is open.

I'd be happy to help debug if I can get you some more information to help.

Brad

**Comment by isometry** [comment]
Thanks for the report!

* What version of macOS are you running?
* What version of Alfred?
* Do you have multiple copies of iTerm2 extracted on your system? If so, what versions, and where are they?
* What state was the iTerm2 window you activated in before you selected the tty? Foreground / background / hidden / minimised?

Also, please try [v1.2](https://github.com/isometry/alfred-tty/releases/tag/v1.2), and let me know whether it behaves differently.
