### ISSUE TITLE
It does not actually jump to iTerm tab

### ISSUE THREAD

**Issue by nikivdev** [isometry/alfred-tty#3]
Not really sure why that happens but pressing on the result does nothing. 

I get this error when running it and selecting some result : 

```Bash
[2017-09-11 23:33:42][ERROR: action.script] /Users/nikivi/alfred/Alfred.alfredpreferences/workflows/user.workflow.E3DFF5F0-0F9C-4174-952D-FB2804EAA834/action-tty.js:1:36: script error: Error on line 2: SyntaxError: Unexpected token '='. Expected a ')' or a ',' after a parameter declaration. (-2700)
```

**Comment by isometry** [comment]
What version of macOS are you running? 10.11?

**Comment by nikivdev** [comment]
Yes. 10.11.6 to be exact.

**Comment by isometry** [comment]
Could you please try [v1.2-beta1](https://github.com/isometry/alfred-tty/releases/tag/v1.2-beta1)? I think the problem was use of ES6 default parameters on my `getenv()` function :-)

**Comment by nikivdev** [comment]
Yay. This works. Thank you.

Although, there is quite an annoying delay you have to wait for to get the results. I really wish this workflow would be as fast [as this one](https://github.com/madvas/alfred-iterm-sessions) which searches through iTerm sessions. If possible of course.

**Comment by isometry** [comment]
Excellent. Try [v1.2-beta2](https://github.com/isometry/alfred-tty/releases/tag/v1.2-beta2) for extra snappy :-)

**Comment by nikivdev** [comment]
Awesome. This is really fast and usable now. Thank you for sharing it. 💛
