### ISSUE TITLE
Add case insensitive search

### ISSUE THREAD

**Issue by nikivdev** [isometry/alfred-tty#6]
Currently if tab has case sensitive name like `sVim`:

![2019-07-24 at 18 03](https://user-images.githubusercontent.com/6391776/61813335-5abbb580-ae3d-11e9-8d89-5b22d7e406f8.png)

If you search for just `svim`, nothing will be returned:

![2019-07-24 at 18 03](https://user-images.githubusercontent.com/6391776/61813353-66a77780-ae3d-11e9-9792-4670586966cc.png)

**Comment by isometry** [comment]
Great idea! Implemented in v1.4.
